<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use App\Admin\Controllers\FileController;
use App\Admin\Controllers\PoemController;
use App\Admin\Controllers\PoemImageController;
use App\Admin\Controllers\PoemImageVisitRecordController;
use App\Admin\Controllers\PoemTagAssignController;
use App\Admin\Controllers\PoemTagController;
use App\Admin\Controllers\SuggestionController;
use App\Admin\Controllers\UserBadgeRecordController;
use App\Admin\Controllers\UserController;
use App\Admin\Controllers\UserPoemHistoryRecordController;
use App\Admin\Controllers\UserPoemImageLikeRecordController;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;
use Slowlyo\OwlAdmin\Admin;

Route::group([
    'domain' => Admin::config('admin.route.domain'),
    'prefix' => Admin::config('admin.route.prefix'),
    'as' => 'admin.',
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 文件
    $router->resource('files', FileController::class);
    // 诗词标签
    $router->resource('poem_tags', PoemTagController::class);
    // 诗词标签分配
    $router->resource('poem_tag_assigns', PoemTagAssignController::class);
    // 诗词图片
    $router->resource('poem_images', PoemImageController::class);
    // 用户诗词收藏记录
    $router->resource('user_poem_image_like_records', UserPoemImageLikeRecordController::class);
    // 诗词
    $router->resource('poems', PoemController::class);
    // 用户
    $router->resource('users', UserController::class);
    // 诗词图片访问记录
    $router->resource('poem_image_visit_records', PoemImageVisitRecordController::class);
    // 用户诗词历史记录
    $router->resource('user_poem_history_records', UserPoemHistoryRecordController::class);
    // 用户勋章记录
    $router->resource('user_badge_records', UserBadgeRecordController::class);
    // 建议
    $router->resource('suggestions', SuggestionController::class);

});
